apiVersion: apps/v1
kind: Deployment
metadata:
  name: price
spec:
  replicas: 1
  selector:
    matchLabels:
      app: price
  template:
    metadata:
      labels:
        app: price
    spec:
      containers:
        - name: price
          image: "{{ .Values.price.image.repository }}:{{ .Values.price.image.tag }}"
          imagePullPolicy: {{ .Values.price.image.pullPolicy }}
          args: ["-b", "0.0.0.0:{{ .Values.price.port }}"]
          env:
            - name: MYSQL_ADDRESS
              value: {{ .Values.mysql.address }}
            - name: MYSQL_PORT
              value: "{{ .Values.mysql.port }}"
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database }}
            - name: MYSQL_USER
              value: {{ .Values.mysql.user }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mysql.password }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
