mode: daemonset

config:
  exporters:
    logging:
      loglevel: debug
    jaeger:
      endpoint: jaeger-collector:14250
      tls:
        insecure: true
  service:
    pipelines:
      logs:
        receivers: [otlp]
        exporters: [logging]
      metrics:
        receivers: [otlp]
        exporters: [logging]
      traces:
        receivers: [otlp]
        exporters: [logging, jaeger]
