mode: daemonset

config:
  processors:
    batch:
      send_batch_size: 8192
  exporters:
    logging:
      loglevel: debug
    jaeger:
      endpoint: jaeger-collector:14250
      tls:
        insecure: true
  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [logging, jaeger]
